trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  packageVersion: '1.0.0'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'packageVersion'
    arguments: '--configuration $(buildConfiguration)'
    packDestination: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    feedType: 'external'
    feedUri: 'https://pkgs.dev.azure.com/1072516/_packaging/1072516/nuget/v3/index.json'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'packageVersion'
